# Generated by Django 6.1.1 on 2026-09-09 11:45

import django.db.models.deletion
from django.db import migrations, models

import drf_playground.apps.catalog.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, unique=True)),
                ("website", models.URLField(blank=True)),
                ("country", models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 code", max_length=2)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                (
                    "isbn",
                    models.CharField(
                        max_length=13,
                        unique=True,
                        validators=[drf_playground.apps.catalog.validators.validate_isbn13],
                        verbose_name="ISBN-13",
                    ),
                ),
                ("published_on", models.DateField(blank=True, null=True)),
                ("page_count", models.PositiveIntegerField(blank=True, null=True)),
                ("language", models.CharField(default="en", max_length=8)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("authors", models.ManyToManyField(related_name="books", to="catalog.author")),
                ("genres", models.ManyToManyField(blank=True, related_name="books", to="catalog.genre")),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="books",
                        to="catalog.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Copy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("barcode", models.CharField(max_length=32, unique=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[("new", "New"), ("good", "Good"), ("worn", "Worn"), ("damaged", "Damaged")],
                        default="good",
                        max_length=10,
                    ),
                ),
                ("acquired_on", models.DateField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="copies", to="catalog.book"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "copies",
                "ordering": ["barcode"],
            },
        ),
    ]
